springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

spring:
  data:
    mongodb:
      database: ${db_name}
      host: ${db_host}
      port: ${db_port}
      authenticationDatabase: ${db_auth}
      username: ${db_user}
      password: ${db_pass}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}
            scope: ${google_scopes}
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs